### ISSUE TITLE
Error: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by jmelero611** [const-ae/mixdir#1]
Hi!

I am running mixdir command to a matrix in which I have patients in columns and some features in rows (introns) and the data in the matrix is categorized in No/Weak/Strong/Very_Strong (as it determines the inclusion of the intron). The dimension of the matrix is 186   x 947. I put here the head of the matrix:

`mat_data[1:6, 1:6]`
```

                         C5RR0ACXX_6_18 C5RR0ACXX_7_23 C5RRKACXX_6_27 C5RRKACXX_7_4
chr1;1922388;1922984;-   "No"           "No"           "No"           "No"         
chr1;6146423;6146664;-   "No"           "No"           "No"           "No"         
chr1;15567269;15567777;+ "No"           "No"           "No"           "No"         
chr1;16029299;16029730;+ "No"           "No"           "No"           "No"         
chr1;16132273;16132377;- "No"           "No"           "No"           "No"         
chr1;20483719;20484366;- "No"           "No"           "No"           "No"         
                         C5RRKACXX_8_13 C5RT7ACXX_2_2
chr1;1922388;1922984;-   "No"           "No"         
chr1;6146423;6146664;-   "No"           "No"         
chr1;15567269;15567777;+ "No"           "No"         
chr1;16029299;16029730;+ "No"           "No"         
chr1;16132273;16132377;- "No"           "No"         
chr1;20483719;20484366;- "No"           "No"
```

What I'm trying to do is clustering the patients according the inclusion of the intron (the feature). When I run mixdir command it appears the following error:

`res <- mixdir(mat_data, max_iter = 100, select_latent = TRUE)`

`Error in if (iter != 1 && !is.infinite(elbo) && elbo - elbo_hist[iter - : missing value where TRUE/FALSE needed`

Curiously, if I restrict the analysis to the first 50 rows, sometimes the error appears and sometimes it does not.

Thanks for your help.

Best regards,
Juan Luis

**Comment by const-ae** [comment]
Hey, that is indeed a confusing error. Did you already find the problem? If it's related to the input, maybe I can at least improve the error message.

Best, Constantin

**Comment by jmelero611** [comment]
In fact, I realized that if I wanted to cluster the patients, then the input should have been the transposed matrix that I show. With the transposed matrix as input, the error does not appear. However, it should not matter for the program if the rows and columns are the other way around, so the problem still is there.

If I can help you to solve the error, I will be pleased to do that :)

Bests,
JL

**Comment by jmelero611** [comment]
Hi,

it seems to happend when there are many features (columns). I have been trying 5k, 1k and 500 to test the command, and it worked for 500 columns (and 872 rows). May be a problem of too big data?

**Comment by const-ae** [comment]
Hi, yes that is possible. If there are so many columns, I think, it is possible, that the program runs into numerical problems. For the class assignment `zeta`, the program sums over the `J` columns and in the end I take the `exp()` of that sum. 
I am not sure that I can really solve that problem (except for rewriting the whole algorithm with higher precision data types), because that is just the way the algorithm works. However, the program should definitely give a more helpful error than the one it is currently providing.

**Comment by const-ae** [comment]
Hi, I wrote a small test case and was able to reproduce your problem. I have changed the code to provide a better error message (1f6654cb9b7ee3ac5683fdda5438aaff2f4ccd54).

Can you maybe try out the latest development version 
```
devtools::install_github("const-ae/mixdir")
```
and see if it does what you would expect?

**Comment by jmelero611** [comment]
Hi,

yes, that was the error and now it raises this message:

```
res <- mixdir(mat_data, max_iter = 100, n_latent = 5)
Error in mixdir_vi(X = X, n_latent = n_latent, alpha = alpha, beta = beta,  : 
  There was an underflow in the calculation of zeta. Cannot continue.
The problem probably came from the large number of columns in the input data (868). Is it possible that you want to work on t(X)?
```

Thank you for the support :)

**Comment by const-ae** [comment]
Just FYI, I have submitted the new version with the improved error message to CRAN (https://cran.r-project.org/package=mixdir)
